# This is a basic workflow to help you get started with Actions

name: TestCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Pyoui-Macmini
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#       - name: Slack notification
#       - run: |
#          text=`echo 새 버전 빌드 *시작!*`
#          json="{\"channel\": \"#flitto_qa\",
#          \"username\": \"GITHUB_ACTION\", 
#          \"icon_emoji\": \":swift:\", 
#          \"attachments\": [
#          { \"color\": \"#0000FF\", 
#          \"text\": \"$text\", 
#          \"author_name\": \"$GITHUB_ACTOR\", 
#          \"mrkdwn_in\": [\"text\"]}]}"
#          curl -s -d "payload=$json" "https://hooks.slack.com/services/T02AAB04R/B01EG5H4WPP/(hashKey)"
         
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: CocoaPods
      - run: pod install
      
      - name: Fastlane
      - run: fastlane testBuild

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
